Transform: AWS::Serverless-2016-10-31
Resources:
 HelloLambdaFuction:
  Type: AWS::Serverless::Function
  DependsOn: MyMountTarget        # This is needed if an AWS::EFS::MountTarget resource is declared for EFS
  Properties:
    Handler: index.handler
    Runtime: python3.6
    InlineCode: |
      def handler(event, context):
        print("Hello, world!")
    ReservedConcurrentExecutions: 30
    Layers:
      - Ref: MyLayer
    Tracing: Active
    Timeout: 120
    FileSystemConfigs:
      - Arn: !Ref MyEfsFileSystem
        LocalMountPath: /mnt/EFS
    Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17' 
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectACL
            Resource: 'arn:aws:s3:::my-bucket/*'
    Events:
      ApiEvent:
        Type: Api
        Properties:
          Path: /path
          Method: get
      ApiEvent2:
        Type: Api
        Properties:
          Method: get
          Path: /group/{user}
          RestApiId: 
            Ref: MyApi







